import { ChatPromptTemplate, MessagesPlaceholder } from "@langchain/core/prompts";
import { StructuredOutputParser, OutputFixingParser } from "langchain/output_parsers";
import { z } from "zod";
import { textLLM } from "./groqClient.js";

// Re-export for use in other modules
export { StructuredOutputParser, OutputFixingParser };

// ─── Zod schemas for structured outputs ──────────────────────────────────────

export const GuideBlockSchema = z.object({
  type:     z.enum(["step", "tip", "code", "explanation"]),
  title:    z.string().optional(),
  content:  z.string().min(1),
  code:     z.string().optional(),
  language: z.string().optional(),
  locked:   z.boolean().default(false),
});

export const ComprehensionQuestionSchema = z.object({
  question:     z.string().min(1),
  options:      z.array(z.string()).length(4),
  correctIndex: z.number().int().min(0).max(3),
  explanation:  z.string().min(1),
});

export const ScreenAnalysisSchema = z.object({
  isInstructional: z.boolean(),
  guideBlocks:     z.array(GuideBlockSchema).max(3),
  comprehensionQuestion: ComprehensionQuestionSchema.nullable(),
  summary:         z.string(),
});

export const ErrorResolutionSchema = z.object({
  diagnosis:    z.string().min(1),
  fixCommand:   z.string().nullable(),
  fixSteps:     z.array(z.string()).nullable(),
  isSetupError: z.boolean(),
  severity:     z.enum(["blocking", "warning", "info"]),
});

// ─── Output parsers ───────────────────────────────────────────────────────────

export const screenAnalysisParser = StructuredOutputParser.fromZodSchema(ScreenAnalysisSchema);

export const errorResolutionParser = StructuredOutputParser.fromZodSchema(ErrorResolutionSchema);

// Self-healing parsers — if the LLM output is malformed, these automatically
// call the LLM again with the parse error to get a corrected response
export const fixingScreenParser  = OutputFixingParser.fromLLM(textLLM, screenAnalysisParser);
export const fixingErrorParser   = OutputFixingParser.fromLLM(textLLM, errorResolutionParser);

// ─── Prompt Templates ─────────────────────────────────────────────────────────

/**
 * Screen analysis prompt — used inside the LangGraph vision node.
 * Includes {format_instructions} from the parser, {session_context} from Redis memory,
 * and {transcript} from Whisper.
 */
export const screenAnalysisPrompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    `You are WKAI, a silent workshop AI. Analyze the instructor's screen.

Session taught so far:
{session_context}

Rules:
- isInstructional: false for idle/browser/desktop screens
- Only emit NEW content not already in session context
- 1-3 guide blocks max, beginner-friendly
- Extract EXACT code, never paraphrase
- comprehensionQuestion only after a major concept completes
- Never hallucinate content

{format_instructions}`,
  ],
  [
    "human",
    [
      {
        type: "image_url",
        image_url: { url: "data:image/png;base64,{frame_b64}", detail: "high" },
      },
      {
        type: "text",
        text: "Instructor audio (last ~30s): {transcript}\n\nAnalyze this screen and respond with the structured output.",
      },
    ],
  ],
]);

/**
 * Error diagnosis prompt — used inside the LangGraph error agent.
 */
export const errorDiagnosisPrompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    `You are WKAI's error resolution engine.
A student in a live coding workshop has hit an error. Diagnose it and provide a fix.

Rules:
- Be concise and student-friendly. No jargon.
- Prefer a single fix command (pip install, npm install, etc.) when possible.
- If multiple steps are needed, list them in fixSteps.
- For code logic bugs, explain what to change in fixSteps.
- If you cannot diagnose it, say so in diagnosis.

{format_instructions}`,
  ],
  ["human", "Student error:\n```\n{error_message}\n```"],
]);

/**
 * Comprehension question refinement prompt.
 * Used in the LangGraph pipeline to improve a question generated by the vision model.
 */
export const questionRefinementPrompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    `You are refining a comprehension check question for a coding workshop student.
Make the question clearer, ensure all 4 options are plausible, and make the
correct answer genuinely require understanding (not just pattern matching).

Session context:
{session_context}

{format_instructions}`,
  ],
  [
    "human",
    `Original question: {question}
Options: {options}
Correct index: {correct_index}
Explanation: {explanation}

Improve this question while keeping the same concept being tested.`,
  ],
]);
